### ISSUE TITLE
icon for recorder

### ISSUE THREAD

**Issue by somratking420** [Kylar101/Recorder.js#1]
Hi @Kylar101  I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by Kylar101** [comment]
Hi @somratking420 ,

Thanks for that. If you are wiling to make me a logo, I will accept a pull request.

Thanks.

**Comment by somratking420** [comment]
Hello,
Good Day, i make a logo icon for your project.I make a 3 logo for you.Which logo do you like? If you want to use this logo in your project, then comment below, I will give you the source file.
![recorder](https://user-images.githubusercontent.com/40878798/42446337-b1fb0b42-8397-11e8-9981-fd775c1eeed4.png)

**Comment by somratking420** [comment]
@Kylar101 .you need any size requirement blow the comment

**Comment by Kylar101** [comment]
Hi,

I like 2a the best, but they all seem out of proportion. Can you make some that are a bit more to scale? I won't accept a pull request for the above.

**Comment by somratking420** [comment]
ok.Thank you.please chack.#2

**Comment by somratking420** [comment]
@kylar101,, please  accept a pull request.
